name: Java CI

on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '22 16 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Beaming
      uses: actions/checkout@v2
      with:
        path: Beaming
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    # Build Beaming
    - name: Build Beaming
      run: mvn -B package -T 1C --file Beaming/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Stage jar
      run: mkdir staging && cp Beaming/target/Beaming*.jar staging
    - name: Rename jar
      run: mv staging/Beaming*.jar staging/Beaming_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Beaming_Dev-Build
        path: staging/Beaming_*.jar
